#ifndef RIPE_ATTACK_PARAMETERS_H
#define RIPE_ATTACK_PARAMETERS_H

enum technique
{
	DIRECT = 100, INDIRECT;
};

enum location
{
	STACK = 400, HEAP, BSS, DATA
};

enum code_ptr
{
	RET_ADDR=300, OLD_BASE_PTR, FUNC_PTR_STACK_VAR, FUNC_PTR_STACK_PARAM,
		    FUNC_PTR_HEAP, FUNC_PTR_BSS, FUNC_PTR_DATA,
		    LONGJMP_BUF_STACK_VAR, LONGJMP_BUF_STACK_PARAM,
                    LONGJMP_BUF_HEAP, LONGJMP_BUF_BSS, LONGJMP_BUF_DATA,
		    STRUCT_FUNC_PTR_STACK,STRUCT_FUNC_PTR_HEAP,
		    STRUCT_FUNC_PTR_DATA,STRUCT_FUNC_PTR_BSS
};

enum function
{
	MEMCPY = 500, STRCPY, STRNCPY, SPRINTF, SNPRINTF, STRCAT, STRNCAT, SSCANF, FSCANF, HOMEBREW
};

enum inject_params
{
	INJECTED_CODE_NO_NOP=200, INJECTED_CODE_SIMPLE_NOP, INJECTED_CODE_POLY_NOP, RETURN_INTO_LIBC, CREATE_FILE, RETURN_ORIENTED_PROGRAMMING
};